[phases.setup]
commands = ["echo Installing Java 17..."]

[phases.install]
commands = ["echo No extra dependencies needed"]

[phases.build]
commands = ["echo Skipping build"]

[phases.start]
commands = ["sh start.sh"]

[env]
JAVA_VERSION = "17"
